import user1 from "../../assets/userImages/user1.jpg";
const userPostData = [
  {
    id: "1",
    userName: "Alex",
    userPic: user1,
    likesCount: 1451,
    caption: "Coffee is the most imp part of my life !",
    type: "sender",
    visible: true,
    category: "all",
    showLike: false,
    isSaved: false,
    isLiked: true,
    date: "12-12-2019 12:12",
    isYourFollower: true,
    isYouFollowing: true,
    commentCount: 12,
    hasBio: false,
    isVerify: false,

  },
  {
    id: "25",
    userName: "Rohit",
    userPic: user1,
    likesCount: 0,
    caption: "Flowers",
    type: "sender",
    visible: false,
    category: "iiii",
    showLike: true,
    isSaved: false,
    isLiked: false,
    date: "12-12-2019 12:12",
    isYourFollower: false,
    isYouFollowing: true,
    commentCount: 258,
    hasBio: false,
    isVerify: true,

  },
  {
    id: "26",
    userName: "Rohit",
    userPic: user1,
    likesCount: 1881,
    caption: "kaan",
    type: "sender",
    visible: false,
    category: "jjjj",
    showLike: false,
    isSaved: false,
    isLiked: false,
    date: "12-12-2019 12:12",
    isYourFollower: false,
    isYouFollowing: false,
    commentCount: 258,
    hasBio: true,
    isVerify: false,

  },
  {
    id: "27",
    userName: "Suyash",
    userPic: user1,
    likesCount: 1,
    caption: "This app is made by Suyash.",
    type: "receiver",
    visible: true,
    category: "kkkk",
    showLike: false,
    isSaved: true,
    isLiked: false,
    date: "12-12-2019 12:12",
    isYourFollower: true,
    isYouFollowing: false,
    commentCount: 258,
    hasBio: false,
    isVerify: false,
  },
];

export default userPostData;