import user1 from "../../assets/userImages/user1.jpg";
const userPostData = [
  {
    id: "1",
    userName: "Alex",
    userPic: user1,
    likesCount: 1451,
    caption: "Coffee is the most imp part of my life !",
    type: "sender",
    visible: true,
    category: "all",
    showLike: false,
    isSaved: false,
    isLiked: true, date: "12/02/2023 12:41",
    isYourFollower: true,
    isYouFollowing: true,
    commentCount: 12,
    hasBio: false,
    isVerify: false,

  },
  {
    id: "2",
    userName: "Martha",
    userPic: user1,
    likesCount: 7,
    caption: "Nothings is better than reading book !",
    type: "receiver",
    visible: true,
    category: "poem",
    showLike: true,
    isSaved: false,
    isLiked: false,
    date: "21/02/2023 12:41",
    isYourFollower: true,
    isYouFollowing: false,
    commentCount: 1,
    hasBio: true,
    isVerify: true,

  },
  {
    id: "3",
    userName: "Aditi",
    userPic: user1,
    likesCount: 0,
    caption: "Waiting for someone to come back !",
    type: "sender",
    visible: false,
    category: "sports",
    showLike: true,
    isSaved: true,
    isLiked: false, date: "21/03/2023 12:41",
    isYourFollower: false,
    isYouFollowing: true,
    commentCount: 0,
    hasBio: false,
    isVerify: false,

  },
  {
    id: "4",
    userName: "Alex",
    userPic: user1,
    likesCount: 51,
    caption: "Coffee is the most imp part of my life !",
    type: "receiver",
    visible: true,
    category: "book",
    showLike: true,
    isSaved: true,
    isLiked: false, date: "31/03/2023 12:41",
    isYourFollower: true,
    isYouFollowing: true,
    commentCount: 258,
    hasBio: true,
    isVerify: true,

  },
  {
    id: "5",
    userName: "Rohit",
    userPic: user1,
    likesCount: 38,
    caption: "car",
    type: "receiver",
    visible: true,
    category: "class",
    showLike: true,
    isSaved: true,
    isLiked: true, date: "12/02/2013 01:03",
    isYourFollower: false,
    isYouFollowing: false,
    commentCount: 2259,
    hasBio: false,
    isVerify: false,

  },
  {
    id: "6",
    userName: "Rohit",
    userPic: user1,
    likesCount: 83,
    caption: "rose",
    type: "sender",
    visible: false,
    category: "football",
    showLike: true,
    isSaved: true,
    isLiked: true, date: "12/02/2023 12:41",
    isYourFollower: true,
    isYouFollowing: false,
    commentCount: 2589,
    hasBio: true,
    isVerify: false,

  },
  {
    id: "7",
    userName: "Rohit",
    userPic: user1,
    likesCount: 1451,
    caption: "Flowers",
    type: "sender",
    visible: false,
    category: "motivation",
    showLike: false,
    isSaved: true,
    isLiked: false, date: "12/02/2023 13:41",
    isYourFollower: false,
    isYouFollowing: true,
    commentCount: 2580,
    hasBio: false,
    isVerify: false,

  },
  {
    id: "8",
    userName: "Rohit",
    userPic: user1,
    likesCount: 1543,
    caption: "kaan",
    type: "receiver",
    visible: false,
    category: "science",
    showLike: true,
    isSaved: true,
    isLiked: false, date: "12/02/2023 12:55",
    isYourFollower: true,
    isYouFollowing: false,
    commentCount: 25821,
    hasBio: true,
    isVerify: true,

  },
  {
    id: "9",
    userName: "Suyash",
    userPic: user1,
    likesCount: 1453,
    caption: "This app is made by Suyash.",
    type: "receiver",
    visible: true,
    category: "music",
    showLike: true,
    isSaved: true,
    isLiked: false, date: "12/02/2023 09:01",
    isYourFollower: false,
    isYouFollowing: true,
    commentCount: 25,
    hasBio: false,
    isVerify: true,

  },
  {
    id: "10",
    userName: "Alex",
    userPic: user1,
    likesCount: 451,
    caption: "Coffee is the most imp part of my life !",
    type: "receiver",
    visible: true,
    category: "ASMR",
    showLike: true,
    isSaved: false,
    isLiked: true, date: "12/02/2023 07:11",
    isYourFollower: true,
    isYouFollowing: true,
    commentCount: 25855, hasBio: true, isVerify: false,

  },
  {
    id: "11",
    userName: "Martha",
    userPic: user1,
    likesCount: 151,
    caption: "Nothings is better than reading book !",
    type: "sender",
    visible: false,
    category: "ASMR2",
    showLike: false,
    isSaved: true,
    isLiked: true, date: "12/02/2023 12:41",
    isYourFollower: false,
    isYouFollowing: true,
    commentCount: 258258, hasBio: false, isVerify: true,

  },
  {
    id: "12",
    userName: "Aditi",
    userPic: user1,
    likesCount: 451,
    caption: "Waiting for someone to come back !",
    type: "sender",
    visible: true,
    category: "ASMR3",
    showLike: false,
    isSaved: false,
    isLiked: false, date: "12/02/2023 12:41",
    isYourFollower: true,
    isYouFollowing: false,
    commentCount: 258, hasBio: true, isVerify: false,

  },
  {
    id: "13",
    userName: "Alex",
    userPic: user1,
    likesCount: 1451,
    caption: "Coffee is the most imp part of my life !",
    type: "receiver",
    visible: false,
    showLike: false,
    category: "ASMR4",
    isSaved: true,
    isLiked: false, date: "12/02/2023 12:41",
    isYourFollower: false,
    isYouFollowing: true,
    commentCount: 258, hasBio: true, isVerify: true,

  },
  {
    id: "14",
    userName: "Rohit",
    userPic: user1,
    likesCount: 145,
    caption: "car",
    type: "receiver",
    visible: false,
    category: "wdefw",
    showLike: true,
    isSaved: true,
    isLiked: false, date: "12/02/2023 12:41",
    isYourFollower: false,
    isYouFollowing: true,
    commentCount: 258,
    hasBio: false, isVerify: false,

  },
  {
    id: "15",
    userName: "Rohit",
    userPic: user1,
    likesCount: 11,
    caption: "rose",
    type: "sender",
    visible: true,
    category: "ASereMR",
    showLike: true,
    isSaved: false,
    isLiked: true, date: "12/02/2023 12:41",
    isYourFollower: true,
    isYouFollowing: false,
    commentCount: 258, hasBio: false, isVerify: true,

  },
  {
    id: "16",
    userName: "Rohit",
    userPic: user1,
    likesCount: 51,
    caption: "Flowers",
    type: "receiver",
    visible: false,
    category: "kaan",
    showLike: true,
    isSaved: false,
    isLiked: false, date: "12/02/2023 12:41",
    isYourFollower: false,
    isYouFollowing: true,
    commentCount: 258, hasBio: false, isVerify: false,

  },
  {
    id: "17",
    userName: "Rohit",
    userPic: user1,
    likesCount: 0,
    caption: "aaaa",
    type: "sender",
    visible: true,
    category: "ASMR",
    showLike: true,
    isSaved: true,
    isLiked: false, date: "12/02/2023 12:41",
    isYourFollower: false,
    isYouFollowing: false,
    commentCount: 258, hasBio: true, isVerify: true,

  },
  {
    id: "18",
    userName: "Suyash",
    userPic: user1,
    likesCount: 14517,
    caption: "This app is made by Suyash.",
    type: "receiver",
    visible: false,
    category: "bbbb",
    showLike: false,
    isSaved: true,
    isLiked: true, date: "12/02/2023 12:41",
    isYourFollower: true,
    isYouFollowing: true,
    commentCount: 258, hasBio: true, isVerify: true,

  },
  {
    id: "19",
    userName: "Alex",
    userPic: user1,
    likesCount: 31451,
    caption: "Coffee is the most imp part of my life !",
    type: "receiver",
    visible: false,
    category: "cccc",
    showLike: true,
    isSaved: false,
    isLiked: false, date: "12/02/2023 12:41",
    isYourFollower: true,
    isYouFollowing: true,
    commentCount: 258, hasBio: false, isVerify: false,

  },
  {
    id: "20",
    userName: "Martha",
    userPic: user1,
    likesCount: 41451,
    caption: "Nothings is better than reading book !",
    type: "sender",
    visible: true,
    category: "dddd",
    showLike: true,
    isSaved: true,
    isLiked: false, date: "12/02/2023 12:41",
    isYourFollower: false,
    isYouFollowing: false,
    commentCount: 258,
    hasBio: true, isVerify: false,

  },
  {
    id: "21",
    userName: "Aditi",
    userPic: user1,
    likesCount: 7451,
    caption: "Waiting for someone to come back !",
    type: "receiver",
    visible: true,
    category: "eeee",
    showLike: false,
    isSaved: true,
    isLiked: true, date: "12/02/2023 12:41",
    isYourFollower: true,
    isYouFollowing: true,
    commentCount: 258,
    hasBio: true, isVerify: true,

  },
  {
    id: "22",
    userName: "Alex",
    userPic: user1,
    likesCount: 1477,
    caption: "Coffee is the most imp part of my life !",
    type: "receiver",
    visible: false,
    category: "ffff",
    showLike: true,
    isSaved: false,
    isLiked: false, date: "12/02/2023 12:41",
    isYourFollower: true,
    isYouFollowing: false,
    commentCount: 258,
    hasBio: false, isVerify: true,

  },
  {
    id: "23",
    userName: "Rohit",
    userPic: user1,
    likesCount: 1751,
    caption: "car",
    type: "sender",
    visible: true,
    category: "gggg",
    showLike: true,
    isSaved: true,
    isLiked: false, date: "12/02/2023 12:41",
    isYourFollower: false,
    isYouFollowing: true,
    commentCount: 258,
    hasBio: true,
    isVerify: true,

  },
  {
    id: "24",
    userName: "Rohit",
    userPic: user1,
    likesCount: 1451,
    caption: "rose",
    type: "receiver",
    visible: true,
    category: "hhhh",
    showLike: false,
    isSaved: true,
    isLiked: true, date: "11/02/2023 12:41",
    isYourFollower: true,
    isYouFollowing: true,
    commentCount: 258, hasBio: false, isVerify: true,

  },
  {
    id: "25",
    userName: "Rohit",
    userPic: user1,
    likesCount: 0,
    caption: "Flowers",
    type: "sender",
    visible: false,
    category: "iiii",
    showLike: true,
    isSaved: false,
    isLiked: false, date: "12/02/2023 12:41",
    isYourFollower: false,
    isYouFollowing: true,
    commentCount: 258, hasBio: false, isVerify: true,

  },
  {
    id: "26",
    userName: "Rohit",
    userPic: user1,
    likesCount: 1881,
    caption: "kaan",
    type: "sender",
    visible: false,
    category: "jjjj",
    showLike: false,
    isSaved: false,
    isLiked: false, date: "12/02/2023 12:41",
    isYourFollower: false,
    isYouFollowing: false,
    commentCount: 258, hasBio: true, isVerify: false,

  },
  {
    id: "27",
    userName: "Suyash",
    userPic: user1,
    likesCount: 1,
    caption: "This app is made by Suyash.",
    type: "receiver",
    visible: true,
    category: "kkkk",
    showLike: false,
    isSaved: true,
    isLiked: false, date: "12/02/2023 12:41",
    isYourFollower: true,
    isYouFollowing: false,
    commentCount: 258,
    hasBio: false,
    isVerify: false,
  },
];

export default userPostData;