import user1 from "../../assets/userImages/user1.jpg";
const UserPostData = [
  {
    id: "1",
    username: "Alex",
    userPic: user1,
    likesCount: 1451,
    caption: "Coffee is the most imp part of my life !",
    type: "sender",
    visible: true,
    category: null,
    showLike: false,
    isSaved: false,
    isLiked: true,
    

  },
  {
    id: "2",
    username: "Rohit",
    userPic: user1,
    likesCount: 0,
    caption: "Flowers",
    type: "sender",
    visible: false,
    category: "iiii",
    showLike: true,
    isSaved: false,
    isLiked: false,
    commentCount: 258,

  },
  {
    id: "3",
    username: "Rohit",
    userPic: user1,
    likesCount: 1881,
    caption: "kaan",
    type: "sender",
    visible: false,
    category: "jjjj",
    showLike: false,
    isSaved: false,
    isLiked: false,
    commentCount: 258,

  },
  {
    id: "4",
    username: "Suyash",
    userPic: user1,
    likesCount: 1,
    caption: "This app is made by Suyash.",
    type: "receiver",
    visible: true,
    category: "kkkk",
    showLike: false,
    isSaved: true,
    isLiked: false,
    commentCount: 258,
  },
  {
    id: "5",
    username: "Alex",
    userPic: user1,
    likesCount: 1451,
    caption: "Coffee is the most imp part of my life !",
    type: "sender",
    visible: true,
    category: null,
    showLike: false,
    isSaved: false,
    isLiked: true,
    

  },
  {
    id: "6",
    username: "Rohit",
    userPic: user1,
    likesCount: 0,
    caption: "Flowers",
    type: "sender",
    visible: false,
    category: "iiii",
    showLike: true,
    isSaved: false,
    isLiked: false,
    commentCount: 258,

  },
  {
    id: "7",
    username: "Rohit",
    userPic: user1,
    likesCount: 1881,
    caption: "kaan",
    type: "sender",
    visible: false,
    category: "jjjj",
    showLike: false,
    isSaved: false,
    isLiked: false,
    commentCount: 258,

  },
  {
    id: "8",
    username: "Suyash",
    userPic: user1,
    likesCount: 1,
    caption: "This app is made by Suyash.",
    type: "receiver",
    visible: true,
    category: "kkkk",
    showLike: false,
    isSaved: true,
    isLiked: false,
    commentCount: 258,
  },
  {
    id: "9",
    username: "Alex",
    userPic: user1,
    likesCount: 1451,
    caption: "Coffee is the most imp part of my life !",
    type: "sender",
    visible: true,
    category: null,
    showLike: false,
    isSaved: false,
    isLiked: true,
    

  },
  {
    id: "10",
    username: "Rohit",
    userPic: user1,
    likesCount: 0,
    caption: "Flowers",
    type: "sender",
    visible: false,
    category: "iiii",
    showLike: true,
    isSaved: false,
    isLiked: false,
    commentCount: 258,

  },
  {
    id: "11",
    username: "Rohit",
    userPic: user1,
    likesCount: 1881,
    caption: "kaan",
    type: "sender",
    visible: false,
    category: "jjjj",
    showLike: false,
    isSaved: false,
    isLiked: false,
    commentCount: 258,

  },
  {
    id: "12",
    username: "Suyash",
    userPic: user1,
    likesCount: 1,
    caption: "This app is made by Suyash.",
    type: "receiver",
    visible: true,
    category: "kkkk",
    showLike: false,
    isSaved: true,
    isLiked: false,
    commentCount: 258,
  },
];

export default UserPostData;